// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmNkXa9KimQLec-hczRAfwptCBxg2hdIo',
    appId: '1:263557142576:web:c789cc1085a2b5321f75f5',
    messagingSenderId: '263557142576',
    projectId: 'ai-chat-ea95d',
    authDomain: 'ai-chat-ea95d.firebaseapp.com',
    storageBucket: 'ai-chat-ea95d.firebasestorage.app',
    measurementId: 'G-7XQ06HW0B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbnNwIE4tj9jFk1qomDtTKBqD7rUwAxg',
    appId: '1:263557142576:android:33f1b65aefe2ae051f75f5',
    messagingSenderId: '263557142576',
    projectId: 'ai-chat-ea95d',
    storageBucket: 'ai-chat-ea95d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9RtHaTpol8zcIiAIVe4gSDYuST8_-mvY',
    appId: '1:263557142576:ios:d3f4639973706b241f75f5',
    messagingSenderId: '263557142576',
    projectId: 'ai-chat-ea95d',
    storageBucket: 'ai-chat-ea95d.firebasestorage.app',
    iosBundleId: 'com.deepakdev.aichat.aiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9RtHaTpol8zcIiAIVe4gSDYuST8_-mvY',
    appId: '1:263557142576:ios:d3f4639973706b241f75f5',
    messagingSenderId: '263557142576',
    projectId: 'ai-chat-ea95d',
    storageBucket: 'ai-chat-ea95d.firebasestorage.app',
    iosBundleId: 'com.deepakdev.aichat.aiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmNkXa9KimQLec-hczRAfwptCBxg2hdIo',
    appId: '1:263557142576:web:f6982e392f246b731f75f5',
    messagingSenderId: '263557142576',
    projectId: 'ai-chat-ea95d',
    authDomain: 'ai-chat-ea95d.firebaseapp.com',
    storageBucket: 'ai-chat-ea95d.firebasestorage.app',
    measurementId: 'G-RTD5Y8FE9C',
  );
}
